### ISSUE TITLE
Any recommendation on cdns that support brotli

### ISSUE THREAD

**Issue by matthewharwood** [ovhemert/gatsby-plugin-brotli#12]
Hey love the idea of brotli but I'm having problems finding an edge/cdn that supports brotli ? any support?

**Comment by ovhemert** [comment]
If you're looking for edge/cdn with Brotli support, I think your best off at putting CloudFlare in front of your site. Many other services still lack support of Brotli compression.
And if you want to host the site yourself, Nginx and Apache have modules for that.
See also: https://richardjgreen.net/brotli-support-azure-web-app/
