### ISSUE TITLE
Use Node.js worker threads

### ISSUE THREAD

**Issue by ovhemert** [ovhemert/gatsby-plugin-brotli#20]
The plugin is currently using the [`worker-farm`](https://www.npmjs.com/package/worker-farm) module to speed up compressions using multiple CPU cores. This seems to give problems on some implementations with Node v13.x and higher.

See: rvagg/node-worker-farm#67 gatsbyjs/gatsby#9027 #19 

To work around the errors, Gatsby sites can still be built on Node v10.x or v12.x

A more permanent solution would be replacing the `worker-farm` module with the Node.js `worker_threads`.
The worker threads are stable since v12.x so that would also mean dropping v10.x support and to bump plugin major version number.

**Comment by japgolly** [comment]
Thanks so much @ovhemert !
