### ISSUE TITLE
Compress html files

### ISSUE THREAD

**Issue by rafcontreras** [ovhemert/gatsby-plugin-brotli#4]
Would it be possible to compress the html files as well?

**Comment by ovhemert** [comment]
I think this would also be possible, although I haven't found that it would speed up my pages to compress the html. When you have an example use case that would benefit from brotli compressing them, I'll consider to support it. Could be a setting, default no html compression, when true.. also html.

You could send me a PR also if you like.

**Comment by gagan0723** [comment]
Hello @ovhemert, I think adding an option to compress `HTML` files can an enhancement.
Like you mentioned the default can be no `HTML` compression. I was also thinking if we can add additional options to compress `JSON` and other formats(`SVG`, etc) as well.

I am not really comfortable with `gatsby` internals so won't be of any help. Happy to help😊.

Reference issues and plugins:
https://github.com/gatsbyjs/gatsby/issues/387#issuecomment-436672441
https://github.com/nsisodiya/gatsby-plugin-html-minifier.git

**Comment by ovhemert** [comment]
Feature just landed in v1.2.0.

Closing issue.

**Comment by gagan0723** [comment]
Thanks for implementing this.
